### ISSUE TITLE
Error while running secbugs

### ISSUE THREAD

**Issue by jpksh90** [squaresLab/security-repair-benchmarks#26]
@ChrisTimperley  I get this error while running secbugs on coreutils benchmark 

```
02:46:46 PM: DEBUG: could not find results artifact [fix-locations.json]
02:46:46 PM: DEBUG: could not find results artifact [localization.json]
02:46:46 PM: DEBUG: could not find results artifact [mutations.json]
02:46:46 PM: DEBUG: could not find results artifact [patches]
02:46:46 PM: DEBUG: could not find results artifact [source-mapping.json]
```

The command I have used is `secbugs repair hifix .` from the bug directory.

**Comment by ChrisTimperley** [comment]
Hi, @jpksh90. This is a feature! 🙂 The secbugs script collects logs and all of the results files for each experiment and stores them in the volume-mounted logs and results directories. These error messages suggest that HiFix is crashing before it can generate `fix-locations.json`. You can look at the log files to see what's happening. You can do so by either looking at them inside the container (/logs), or on the host (security-repair-benchmarks/logs).

**Comment by ChrisTimperley** [comment]
> 
> 
> Yes, I did that. I guess you also need to `install` the hifix volume. It would be great if you can please update the README.

Are you sure? The default make rule runs `./install` by default.
https://github.com/squaresLab/HiFix/blob/main/docker/Makefile#L1
